### ISSUE TITLE
New way to create AOI Boundary?

### ISSUE THREAD

**Issue by LManak** [mthomp89/landslide-detect#31]
I am wondering if we can create a class or something similar for getting the Bounding Box instead of having to rely of our JSON files. Can we do something where it matches the geometry filter in the image_search function?

**Comment by mthomp89** [comment]
Definitely an option! Had the same thought after experiencing the errors with the API. We don't know how big to make the bounding boxes for each site which is why I'm trying to using the ee.Geometry.Point.buffer() function. Think we're just out of time unfortunately - I suspect it'd take a week minimum to work that out. Definitely capture it as a future work element.
